### ISSUE TITLE
search only works every 2nd time

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#15]
If you search for the 1st time, you don't get any result someteims.
If you press on the search logo afterwards, you'll get a result.

**Comment by gschwann** [comment]
Works fine for me.
Please have a look again - now an error message shows up on the bottom in case or loading errors:
https://github.com/gschwann/Baugeschichte/commit/cc290aeb2cee8e3a93b254da5862c5b1ba82e5bc

**Comment by Flexmaen** [comment]
Seems to work.
