### ISSUE TITLE
Nach Suche im Vollbild

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#16]
Im Quermodus landet man nach der Suche in der Vollbild-Detailansicht.
Dann kommt man auch durch den Kartenknopf nicht zurück auf die Karte (eigener Bug), auch beim rechts und wieder zurückippen bleibt der Vollbild-Modus.

**Comment by gschwann** [comment]
fixed in
https://github.com/gschwann/Baugeschichte/commit/05db4595b9ae485e86bd5512b30bb2f44a651110
