### ISSUE TITLE
Karten-Knopf geht nicht immer

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#17]
Der Karten-Knopf bringt einen nicht immer zurück auf die Kartei.

Vor allem wenn zB gerade eine Suchanfrage offen ist, oder man in der Detailansicht eines Suchergebnisses ist.

**Comment by gschwann** [comment]
Fixed in commit https://github.com/gschwann/Baugeschichte/commit/9fc4c0157b8cf0ceb8f9569c59a307074d42590b
