### ISSUE TITLE
Bild fehlt Technikerstraße 4

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#18]
Entweder ein Fehler in der Eingabe der nicht abgefangen wird.
Oder es hat damit zu tun, dass das Bild von der Wikipedia kommt (wobei das ja bei anderen Adressen, u.a. Liebiggasse 9 klappt).
Es scheint aber der zweite ref-tag in der App nicht angezeigt zu werden.

**Comment by gschwann** [comment]
Liebiggasse 9 zeigt bei mir 2 Bilder (vor/nach der Aufstockung).
@Flexmaen bitte nochmal testen

**Comment by Flexmaen** [comment]
Ja, wie oben geschrieben klappt die Liebbiggasse. Ich habe sieh nur erwähnt weil ich getestet habe, ob das ev. an dem Wikipedia-Bildmaterial liegt (und ich nicht sicher war ob das überhaupt auf unserem Server gecached wird).

D.h. die Ursache warum die Technikerstraße 4 nicht klappt muss eine andere sein.

**Comment by gschwann** [comment]
Fixed by commit https://github.com/gschwann/Baugeschichte/commit/edc5142d1ca8e23fd48802f993162a9f6c9c601c

**Comment by gschwann** [comment]
Sorry für das "Verlesen". Ist nun gefixt :)
