### ISSUE TITLE
Karten-Knopf wirft einen aus der Route raus

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#19]
Hat man eine Route gewählt, geht zB in die Detail-Ansicht und drückt man den Karten-Knopf, dann fliegt man wieder ganz aus der Route raus (und müsste sie wieder neu auswählen).

Das Verhalten ist sicher nicht optimal, so fliegt man dauernd aus der Route. Im Prinzip sollte man aber auf die Karten-Ansicht kommen, auf der noch die Route ausgewählt ist.

Dabei stellt sich dann allerdings die Frage:
Wie kommt man dann künftig aus der Route raus?

Eine Möglichkeit wäre, dass erneutes Drücken des Karten-Knopfes einen mit einer Sicherheitsabfrage "Wollen sie die Route verlassen?" aus der Route schmeißt. (So lange die Route aktiv ist, könnte der Kartenknopf entsprechend anders aussehen).

**Comment by Flexmaen** [comment]
Das gleiche Verhalten, wäre dann eigentlich auch gewünscht, wenn man eine Kategorie ausgewählt hat. (D.h. 1x Kartenknopf bnringt einen zurück aus der Kategorie, 2x verlässt die Kategorie).

**Comment by Flexmaen** [comment]
Man fliegt nach wie vor aus der Route.

**Comment by gschwann** [comment]
Wenn Details offen sind, wird das geschlossen wenn man auf die Karte drückt.
Dann gibt es erst beim zweiten mal das "reset".
https://github.com/gschwann/Baugeschichte/commit/26292b9eb58d5da1d69500fef46c72fcf9d27911
