### ISSUE TITLE
Location ohne Fokus

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#20]
Der Location-Knopf bietet momentan die Möglichkeit
- Aus
- An, mit automatischer Zentrierung

Ein zusätzlicher Modus
- An, ohne automatischer Zentrierung
wäre praktisch.
Dieser sollte autmatisch aktiviert werden sobalt man die Location an hat, aber die Karte manuell verschiebt. Ein Druck auf den Location-Knopf sollte einen dann wieder in den Modus mit automatischer Zentrierung bringen (und ein zweiter Druck die Location wieder wie üblich deaktivieren).

**Comment by Flexmaen** [comment]
Sollen wir das so lassen, oder soll der Fokussierungs-Modus automatisch verlassen werden, wenn man die Karte verschiebt? Was meinst Du?

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/dfd702803da3e074141b4252bb3aee4d4727f67d
