### ISSUE TITLE
Mehrsprachigkeit

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#22]

**Comment by Flexmaen** [comment]
Geht nun rudimentär, hat aber noch folgendes Problem:
Wenn man auf englisch umschaltet, dann sind auch die Bilder weg. Die Bilder bleiben allerdings immer die gleichen, es gibt nur verschiedene Sprachen für Titel und Textfeld. Der Rest - Bildbeschriftung, Diskussion etc. kennt nur eie Sprache.

Und wenn man einmal die Sprache umgeschalten hat und eine Adresse anklickt die dann zB nicht auf Englisch existiert, dann kommt gar nichts. Dann muss man erst mal im "Blindflug" eine zweisprachige Adresse finden, um wieder zurückschalten zu können.

**Comment by gschwann** [comment]
Fixed with https://github.com/gschwann/Baugeschichte/commit/0360252b056c5192b8f28c6a31caf3c251cefcb8
