### ISSUE TITLE
Überarbeitung der Darstellungsseiten

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#23]
Pfeile nur wenn mehrere Häuser
Diskussion, Info extra darstellen
(In Zusammenarbeit mit der mehrsprachigen Api-Überarbeitung)

**Comment by gschwann** [comment]
Pfeile gibt es nun mit https://github.com/gschwann/Baugeschichte/commit/96cb4e1c4c2c619312fff97728fd5315d78e5cbc

**Comment by Flexmaen** [comment]
Das ist jetzt eigentlich ziemlich perfekt.

Einzige offene Frage wäre für ich ob die Pfeile bei den Bildern nicht einfach nur einmal nach links/rechts schalten sollen, statt ebenfalls wie die unteren Pfeile zum Anfang der Sektion zu hupfen.

**Comment by Flexmaen** [comment]
Darstellung passt. Für Bilder-Wischen eine extra Issue aufgemacht.
