### ISSUE TITLE
Route: Andere Marker sollten erhalten bleiben

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#24]
Bei einer Route werden jetzt nur die Marker der Einträge in der Route angezeigt.

Eventuell wäre es sinnvoll, alle Marker zu erhalten und den Routen-Markern eine auffällige andere Farbe zu geben.

**Comment by gschwann** [comment]
Fixed in revision
https://github.com/gschwann/Baugeschichte/commit/05db4595b9ae485e86bd5512b30bb2f44a651110
