### ISSUE TITLE
API Level (Android)

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#25]
Generell wäre es wünschenswert einen möglichst niedrigen [API-Level](https://de.wikipedia.org/wiki/Liste_von_Android-Versionen) zu verwenden. 

Blackberry 10 Geräten unterstützen Android bis zum API-Level 17/18, siehe [hier](https://developer.blackberry.com/android/apisupport/unsupported_api_jellybean_appfeatures.html)., Level 16 würde noch Kompatibilität zu Android 4.1 bedeuten. Derzeit geht die APK noch nicht auf BB10-Geräten.

**Comment by gschwann** [comment]
Minimal level is 9, preferred is 14. I fear this a Qt5 issue with the BB10 Android compatibility layer.

**Comment by Flexmaen** [comment]
Glaub ich nicht. Unsere ersten Releases mit QT5 haben auf BB10 noch funktioniert.

**Comment by Flexmaen** [comment]
Geht nun zumindest auf BB10. Eventuell war auch [dieser Bug ](https://supportforums.blackberry.com/t5/BlackBerry-10-Functions-and/OS-10-3-2-2876-BUG-android-apps-do-not-uninstall/td-p/3153625)der Grund.
