### ISSUE TITLE
andere Farbe für angewählten Marker

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#26]
Es wäre toll, wenn der gerade angetippte Marker eine andere Farbe bekommt, das der Marker von der gerade angezeigten Adresse.

Beim zoomen und verschieben tippt man manchmal versehentlich auf einen anderen Marker - dann sieht man nicht mehr welcher nun gerade angezeigt wird.

**Comment by gschwann** [comment]
fixed in
https://github.com/gschwann/Baugeschichte/commit/05db4595b9ae485e86bd5512b30bb2f44a651110
