### ISSUE TITLE
Bilder bzw. Fehlermeldung dazu fehlt

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#27]
in der Version vom 23.5. fehlen momentan die Bilder, bzw. kommt in dem Fall keine Fehlermeldung, warum das bild nicht geladen wird.

**Comment by gschwann** [comment]
Fixed with commit https://github.com/gschwann/Baugeschichte/commit/dacf9f49a0bd46aeaeedb7edf8cc00eb1ef16bfd
Fehler mit URL wird angezeigt falls nicht geladen werden konnte
