### ISSUE TITLE
Suchfeld hat zwei Texte übereinander

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#30]
Suchfeld had zwei Schriften übereinander. Weiß nicht ob das überall pass iert - auf Bluestacks getestet, etwas eingeippt und ein paar Buchstaben wieder weggelöscht, dann passiert das:
![suche_overlay](https://cloud.githubusercontent.com/assets/6330276/16357417/5f8b969c-3af6-11e6-8fb1-0d178a9a764f.png)

Am Handy habe ich dieses Verhalten nicht gehabt - dort ist allerdings auch keine Rechtschreibkorrektur aktiv. Die drei unterstrichenen Buchstaben lassen sich wegen der Rechtschreibkorrektur nicht weglöschen - ev. der Grund warum das Eingabefeld sich wieder so verhält als ob es leer wäre.

**Comment by Flexmaen** [comment]
Das habe ich auch bei einem Android-Tablet reproduzieren können!
Standard Google Tastatur mit eingeschaltener Rechtschreibprüfung verwendet, und so lange Wortteile unterstrichen werden verschwindet "Adresse..." nicht aus dem Textfeld.

**Comment by gschwann** [comment]
Fixed in commit https://github.com/gschwann/Baugeschichte/commit/d5301216db50701b75a49382cdabbc8f8c376c24
