### ISSUE TITLE
Textfelder sollten automatisch Fokus bekommen

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#32]
Wenn man auf das Feld für "Suche" oder "Kategorien" tippt, dann kann man nicht gleich darauf etwas eingeben sondern muss zuvor nochmal in das Textfeld klicken. Der Fokus könnte automatisch gleich ins Textfeld gelegt werden.

**Comment by Flexmaen** [comment]
Nachsatz:
Eigentlich ist das nur bei "Suche" nötig. Die Kategorien und Routen brauchen (vorerst) kein Textfeld.

Bei den Routen hat dieses auch keine Funktion, und es ist sogar hinderlich, da die On-Screen-Tastatur aufpoppt und bei manchen Geräten die Liste verdeckt.

Daher: Fokus im Suchfeld bei der Suche, Suchfeld bei den Kategorien und Routen abschalten. Eventuell später mal eine Auswahl der Stadt andenken.

**Comment by Flexmaen** [comment]
Einstufung als Bug, weil das Suchfeld bei der Route ja nicht funktioniert. Kann man aber dort dann entfernen.

**Comment by gschwann** [comment]
Fix in https://github.com/gschwann/Baugeschichte/commit/034a3ce8929b18b15f337a2481393c5ae13d3ae9
