### ISSUE TITLE
Wischverhalten der Bilder

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#33]
Das Wischverhalten beim durchblättern der Bilder ist sehr seltsam und könnte auch deaktiviert werden wenn es nur ein Bild gibt. (So wie das jetzt aussieht, wäre es ohnehin gut erkenntlich ob es ein oder mehrere Bilder gibt - eine zusätzliche Kennzeichnung ob man nun wischen kann oder nicht wäre eigentlich nicht nötig).

**Comment by Flexmaen** [comment]
Hat nun offenbar einen schnellen fix. Wäre aber nicht schlecht, wenn gleich auf den ersten Blick ersichtlich ist, ob es hier nur ein Bild gibt, oder ob man blättern kann.

**Comment by gschwann** [comment]
Es gibt nun Pfeile die das anzeigen: https://github.com/gschwann/Baugeschichte/commit/96cb4e1c4c2c619312fff97728fd5315d78e5cbc
