### ISSUE TITLE
Fehlermeldung wenn Bilder nicht geladen werden können

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#35]
Wenn ein Bild nicht geladen wird, dann kommt an dieser Stelle keine Fehlermeldung.
D.h. es ist nicht erkenntlich, ob es hier kein Bild gibt, oder ob etwas nicht geladen werden konnte.

**Comment by Flexmaen** [comment]
Wir haben übrigens Bilder im System eingetragen die es nicht gibt - als Beispiel:
http://www.grazwiki.at/Alberstra%C3%9Fe_1

Dadurch kommt ev. zustande das weder ein Bild, noch eine Fehlermeldung angezeigt wird.
Die Frage ist, ob das wirklich ein Fall ist, denn wirklich die App abfangen muss, oder ob wir da nicht einfach am Server die Daten bereinigen.

**Comment by Flexmaen** [comment]
Schlecht wäre es vielleicht nicht, wenn man da auch prüft ob wirklich auch ein Bild daherkommt.

**Comment by gschwann** [comment]
Now a test is shown when there is no image for the building fixed in https://github.com/gschwann/Baugeschichte/commit/7014b8053c882f2b67033d7794b06a153ed15f2b
