### ISSUE TITLE
App-Beenden Abfrage funktioniert nicht

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#37]
Betrifft Android:
Drückt man den Zurück-Knopf in der Hauptansicht dann kommt die Frage:
"Soll Baugeschichte beendet werden Nein/Ja".
Sie wird aber nicht beendet, wenn man "ja" klickt.

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/26292b9eb58d5da1d69500fef46c72fcf9d27911
