### ISSUE TITLE
Zurück-Knopf wirft einen manchmal aus der App

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#38]
Habe das nun 2x wie folgt reproduziert:
1. App frisch starten
2. Auf die Suche klicken, irgendetwas suche, aber keines der Ergebnisse anklicken
3. Auf die Routen klicken während die Suchergebnisse noch offen sind
4. Irgendeine Adresse auswählen und in die Detailansicht gehen
5. Zurückknopf drücken und man fliegt aus der App

**Comment by gschwann** [comment]
Should be fixed in https://github.com/gschwann/Baugeschichte/commit/26292b9eb58d5da1d69500fef46c72fcf9d27911
Please check
