### ISSUE TITLE
Titel der App / Versionsnummern

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#39]
Die App steht im Menü als "Baugeschichte V2".

Vielleicht kann man nur "Baugeschichte" nennen und dafür dann eine Sinnvolle Versionsnummer ab 2.x (für die Stores vergeben, die man bei den verschiedenen Systemen konsistent hält.

Versionsnummer im Playstore derzeit 1.1 (hat die alte App mit 0.0.1 abgelöst), Nr. im iTunes derzeit 1.0.1 (ist aber die alte App).

Würde daher Vorschlagen mit 2.x zu starten, die Nr. unter verschiedenen Plattformen gleich zu halten und dafür aus dem Titel der App zu nehmen.

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/4ae6186f50ff673a97b781af400c739407a34fa0
