### ISSUE TITLE
Datenmix bei schneller Auswahl mehrerer Marker hinterinander

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#40]
Das Problem ist leider noch nicht ganz behoben:

Klickt man auf einen Marker und schnell auf einen anderen dann kommt es noch immer zu einer Datenmischkulanz.

Und zwar:
- nicht sofort nochmal klickt, sondern etwas wartet
- wenn man das zB mit Hauptplatz 1 und Herrengasse 3 macht, dann bekommt die Herrengasse 3 den englischen Text vom Rathaus

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/d44263fec899754ab5dc9a64b85008a8765b0b70
