### ISSUE TITLE
manueller Bildwechsel löst Sprung zum ersten Bild der Sektion aus

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#43]
Fehler bzw. unerwünschtes Verhalten beim hin und herwechseln zwischen den Bildern:
Wischt man ein Bild nach links, dann bewegen sich die Bilder automatisch zum ersten Bild der Sektion.

Beispiel Hauptplatz 1:
Wischt man vom vierten Bild ein Bild nach links, dann bewegen sich die Bilder plötzlich automatisch zum allerersten Bild. Das verhalten ist erwünscht wenn man unten zwischen den Sektionen hin und her schaltet, aber nicht wenn man nur ein Bild nach links wischen will.

**Comment by gschwann** [comment]
Fixed in commit https://github.com/gschwann/Baugeschichte/commit/9255fd7408bd7276f7611f0ad805c03116ab603a

**Comment by Flexmaen** [comment]
Also bei mir ist das Problem noch nicht behoben, da hat sich eigentlich nichts verändert.
Version 1.0.0.3 (Beschreibung Baugeschichte 2.0.1)

Teste nochmal bei Hauptplatz 1.
Geh zum vierten Bild (das erste Schwarzweiß-Foto), und anschließend wieder zurück zum dritten: Die Ansicht bleibt nicht beim dritten, sondern hupft dann wieder zum ersten Bild.

**Comment by Flexmaen** [comment]
Ist nun ja behoben.
