### ISSUE TITLE
Formatierungen und Links im Textfeld

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#44]
Textfeld sollte Formatierungen und interne Links unterstützen.

Beispiel:
http://www.grazwiki.at/Schillerstra%C3%9Fe_27 (interner Link auf Schillerstraße 29, könnte innerhalb der App geöffnet werden)
http://www.grazwiki.at/Liebiggasse_9 (Referenzangabe mit externem Link, müsste in Browser aufgehen)

Frage ist dabei ob das Textfeld auch Formatierungen wie Fett, kursiv etc. unterstützen könnte

**Comment by gschwann** [comment]
Fixed https://github.com/gschwann/Baugeschichte/commit/41c05cdf00749b4398bfa93c22f477f8f6fb62ff
