### ISSUE TITLE
fehlende Marker beim Umschalten der Kategorie

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#45]
Wenn man manchmal die erste Kategorie wählt, dann erscheinen keine Marker, oder nur die, die im Cache sind. Das passiert man man zB zuvor eine Route ausgewählt hat usw., oder man in einer Detailansicht war.

**Comment by gschwann** [comment]
Ist man in einer Kategorie, dann werden nur Marker dieser Kategorie gezeigt.
Soll das Verhalten anders sein?

**Comment by Flexmaen** [comment]
Ich schließe das mal - das Verhalten der Marker muss mit dem neuen QT eh neu evaluiert werden.
