### ISSUE TITLE
weißer Hintergrund verschiebt sich

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#47]
Wenn man den Bild/Text-Trenner verschiebt, dann verschiebt sich der weiße Bereich hinter dem Bild genau gegenverkehrt dazu.

Kein schwerer Bug, aber sieht nicht schön aus. Vielleicht sowieso gleich den ganzen Hintergrund weiß machen?

**Comment by gschwann** [comment]
Fixed in commit https://github.com/gschwann/Baugeschichte/commit/4fa551a528441e248bd9dc4c9ed7dd85979c80b0
