### ISSUE TITLE
Detailansicht auch öffnen wenn der Marker das 2. Mal angetippt wird.

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#48]
Drückt man 1x auf den Marker, dann verfärbt er sich blau und macht eine Textbox mit der Adresse auf.

Die Tests haben gezeigt, dass die Leute anschließend mehrmals auf den Marker drücken, statt auf das Textfeld zu tippen. Daher sollte die Detailansicht auch aufgehen, wenn man auf den nun blau gefärbten Marker tippt.

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/1d4c30534324e636da4f4c47a443120043731697
