### ISSUE TITLE
Marker sollen beim zoomen und verschieben nicht gewählt werden

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#49]
Beim zoomen und verschieben erwischt man eigentlich immer versehentlich einen Marker.
Könnte man das irgendwie verhindern/verbessern, oder ist das schwierig?

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/2d8d58dc1949be512c7168f54954dda622dcc037
