### ISSUE TITLE
Text bei Route/Suche abgeschnitten

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#50]
Vor allem bei den Routen ist der Text u.a. beim iPhone sehr groß und nicht vollständig sichbar.

Lösungsmöglichkeiten wären: kleiner Text und/oder Zeilenumbruch, oder durchscrollen.
Ev bei der Route auch die Stadt in einer extra Zeile, oder nach Stadt sortieren.

**Comment by gschwann** [comment]
Fixed in https://github.com/gschwann/Baugeschichte/commit/d0af202793e80c05bf8f5c7933972b1287e859dc
