### ISSUE TITLE
Positions-Punkt Optimierung

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#51]
Der Positions-Punkt würde an die Zoomstufe angepasst gehören, bei hoher Zoomstufe ist er zu groß und geht teils über mehrere Straßen.

Bei niedriger Zoomstufe hingegen, könnte einen ein klick auf diesen Punkt in eine höhere Zoomstufe im entsprechenden bereich bringen.

**Comment by gschwann** [comment]
Ich habe den Punkt etwas kleiner gemacht (etwas großer als die Marker). Aber die Größe würde ich fix lassen (ist bei anderen karten Apps auch so - z.B. Google Maps).
