### ISSUE TITLE
Karte soll in Graz starten, wenn keine GPS Koordinaten vorliegen

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#61]
Bitte überprüfen:
Ich habe die App (2.0.3.) auf meinem Tablet ohne GPS ausprobiert. Beim Start der App befindet man sich mitten im Kongo.

So lange keine Koordinaten bekommen werden sollte der Start in Graz erfolgen.

**Comment by gschwann** [comment]
Fixed nasty Qt bug with https://github.com/gschwann/Baugeschichte/commit/b08753c7ab4887bac0d6aba9322a4c0a4dab8690
