### ISSUE TITLE
URLs werden nicht extern geöffnet sondern bringen App zu Fehlfunktion

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#65]
Klickt man auf eine URL, so kommt eine Fehlermeldung in der App. Daraufhin öffnet sich auch kein weiterer Eintrag mehr in der App. Betrifft derzeit IOS und Android.

![ios_link_bug_1](https://cloud.githubusercontent.com/assets/6330276/26401762/b9cb0010-4087-11e7-8282-d1c51cc4e062.jpg)
![ios_link_bug_2](https://cloud.githubusercontent.com/assets/6330276/26401764/b9d25ec8-4087-11e7-88fc-a02607f82b3d.jpg)
![ios_link_bug_3](https://cloud.githubusercontent.com/assets/6330276/26401763/b9d1d548-4087-11e7-946f-d3299568db17.jpg)

**Comment by gschwann** [comment]
Fixed with commit 1d1ce9bc5ba2ebf7c8c63cd63be623f456a9743f
