### ISSUE TITLE
Wenn mehere Bilder für ein Gebäude, dann wird bei Vollbild manchmal das falsche Bild gezoomt

### ISSUE THREAD

**Issue by gschwann** [gschwann/Baugeschichte#68]
Beispiel Graz Hauptzlatz 1

**Comment by Flexmaen** [comment]
Das scheint jetzt verbessert zu sein, allerdings tritt der Fehler noch auf wenn man das Gerät kippt, während man ein Vollbild offen hat:

1. Rathaus aufmachen
2. Zum letzten Bild ("um 1550 erbautes Rathaus") gehen.
3. Vollbild machen
4. Gerät nach links kippen
5. Vollbild wieder weg
5. ein Bild davor (nach links) gehen
6. wieder Vollbild machen => es kommt ein anderes Bild

Lustig ist: Wenn man wieder nach rechts kippt scheint wieder alles zu passen.

**Comment by Flexmaen** [comment]
Ist nun behoben, App scrollt dann automatisch zum richtigen Bild.
