### ISSUE TITLE
Text-Bubble muss 2x angetippt werden

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#76]
Tippt man zuerst auf den Marker, poppt der Text mit der Adresse auf.
Tippt man dann auf den Text, passiert zunächst nichts.
Tippe ich nochmal drauf, erst dann geht der Eintrag
auf. Das sollte schon beim ersten mal erfolgen.

**Comment by gschwann** [comment]
Grund ist dass die MapGesture ein Pan erkennt und das Event "frisst" - zumindest unter Android.
mal sehen wie man das umgehen kann...
