### ISSUE TITLE
App beendet beim Zurück-Knopf

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#77]
Drückt man in den Settings den Android-Zurück-Knopf, dann ist die App weg.

Sie sollte eigentlich zur Karte zurück,

**Comment by Flexmaen** [comment]
Die App beendet auch so manchmal, wenn man den Zurück-Knopf drückt. Habe daher das Topic geändert.

**Comment by gschwann** [comment]
Closed with commit f77b9df35443cced2abdec59e87c08d20e2d7568
