### ISSUE TITLE
marker problem with new QT

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#83]
Mit der neuen QT Version ist die Karte flüssiger - allerdings werden auch in der vollen Zoomstufe nicht alle Marker angezeigt.

neue Version (Marker fehlt):
![screenshot_20181018-003444](https://user-images.githubusercontent.com/6330276/47141420-ec036780-d2c0-11e8-901d-3b763f55d5c5.png)

alte Version (alle Marker da):
![screenshot_20181018-003732](https://user-images.githubusercontent.com/6330276/47141421-ec036780-d2c0-11e8-8e69-98ae5e10d0b9.png)

neue Version (obwohl Marker beim Zoomen entfernt werden, entsteht ein schwarzer Fleck):
![screenshot_2018-10-18-10-09-29](https://user-images.githubusercontent.com/6330276/47141427-f160b200-d2c0-11e8-97aa-06eae1252525.png)

**Comment by gschwann** [comment]
Ist mit dem neuesten Release gefixt.
