### ISSUE TITLE
keine älteren Gebäude bei drei Sprachen

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#89]
Beispiel Hauptplatz 1:
Wird eine dritte Sprache hinzugefügt (in dem Fall mit "sl" für Slowenisch ins mittlere Feld), dann waren in der ab nur 2 Sprachen und die älteren Gebäude wurden nicht gezeigt.

Die Api hat in dem Fall folgendes geliefert:
{"action":"getbuildingsdetail","parameters":"title","version":"1","title":"Hauptplatz_1","payload":[{"lang":"de", "title":"aktuell", "text":"M\u00e4chtiger Baublock mit dominantem kuppelbekr\u00f6ntem Mittelrisalit, Eckt\u00fcrmen und sp\u00e4thistoristisch-altdeutscher Fassadierung, 1887\/89 nach Entwurf von Alexander von Wielemans und Theodor Reuter unter Einbeziehung von Bauteilen des klassizistischen Vorg\u00e4ngerbaus errichtet. Vom urspr\u00fcnglich reichen Figurenschmuck sind nur wenige Standbilder erhalten. Im Inneren stammen die Stiegenanlage sowie Holzkassettendecken noch aus der Bauzeit. Der repr\u00e4sentativste Raum ist der \u00fcber zwei Geschosse reichende Sitzungssaal des Gemeinderates mit intakter sp\u00e4thistoristischer Ausstattung.","images":[{"imageName":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Graz_-_Rathaus2.jpg/640px-Graz_-_Rathaus2.jpg", "imageDescription":" 2011"},{"imageName":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Graz_Rathaus_4.jpg/640px-Graz_Rathaus_4.jpg", "imageDescription":"Rathaus vom Schlo\u00dfberg 2008"},{"imageName":"images/b/b2/Z1_709b.jpg", "imageDescription":"AGIS 2002"}]},{"lang":"en","title":"City Hall","text":"Rebuilt 1887\/89 by Alexander von Wielemans and Theodor Reuter."},{"lang":"sl","title":"Mestna hi\u0161a","text":null},{"lang":"de", "title":"Vorg\u00e4ngerbauten", "text":"Von 1803 bis 1807 nach den Pl\u00e4nen des Grazer Architekten Christoph Stadler umgebautes Rathaus.","images":[{"imageName":"images/thumb/7/7e/Rathaus_graz_stadler.jpg/640px-Rathaus_graz_stadler.jpg", "imageDescription":" "}]},{"lang":"en","title":"old city hall","text":"Rebuilt 1803 to 1807 by plans from Christoph Stadler."},{"lang":"sl","title":"Mestna hi\u0161a","text":null},{"lang":"de", "title":"erstes Rathaus", "text":"Um 1550 erbautes Rathaus.","images":[{"imageName":"images/thumb/4/43/Rathaus_alt.jpg/640px-Rathaus_alt.jpg", "imageDescription":" "}]},{"lang":"en","title":"First City Hall","text":"City hall built about 1550."},{"lang":"sl","title":"Mestna hi\u0161a","text":null},{"title":"Info ", "text":"Hauptplatz_1\n8010 Graz\nSteiermark\n\u00d6sterreich\n\n47.070725, 15.438458333333\nmehr unter http:\/\/baugeschichte.at\/Hauptplatz_1","images":[{"imageName":"skins/common/images/logo_baugeschichte.png", "imageDescription":""}]}]}

**Comment by gschwann** [comment]
Ich bekomme vom Server keine dritte Sprache:

http://baugeschichte.at/app/v1/getData.php?action=getBuildingDetail&name=Hauptplatz%201

{"action":"getbuildingsdetail","parameters":"title","version":"1","title":"Hauptplatz 1","payload":[{"lang":"de", "title":"aktuell", "text":"M\u00e4chtiger Baublock mit dominantem kuppelbekr\u00f6ntem Mittelrisalit, Eckt\u00fcrmen und sp\u00e4thistoristisch-altdeutscher Fassadierung, 1887\/89 nach Entwurf von Alexander von Wielemans und Theodor Reuter unter Einbeziehung von Bauteilen des klassizistischen Vorg\u00e4ngerbaus errichtet. Vom urspr\u00fcnglich reichen Figurenschmuck sind nur wenige Standbilder erhalten. Im Inneren stammen die Stiegenanlage sowie Holzkassettendecken noch aus der Bauzeit. Der repr\u00e4sentativste Raum ist der \u00fcber zwei Geschosse reichende Sitzungssaal des Gemeinderates mit intakter sp\u00e4thistoristischer Ausstattung.","images":[{"imageName":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Graz_-_Rathaus2.jpg/640px-Graz_-_Rathaus2.jpg", "imageDescription":" 2011"},{"imageName":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Graz_Rathaus_4.jpg/640px-Graz_Rathaus_4.jpg", "imageDescription":"Rathaus vom Schlo\u00dfberg 2008"},{"imageName":"images/b/b2/Z1_709b.jpg", "imageDescription":"AGIS 2002"}]},{"lang":"en","title":"City Hall","text":"Rebuilt 1887\/89 by Alexander von Wielemans and Theodor Reuter."},{"lang":"de", "title":"Vorg\u00e4ngerbauten", "text":"Von 1803 bis 1807 nach den Pl\u00e4nen des Grazer Architekten Christoph Stadler umgebautes Rathaus.","images":[{"imageName":"images/thumb/7/7e/Rathaus_graz_stadler.jpg/640px-Rathaus_graz_stadler.jpg", "imageDescription":" "}]},{"lang":"en","title":"old city hall","text":"Rebuilt 1803 to 1807 by plans from Christoph Stadler."},{"lang":"de", "title":"erstes Rathaus", "text":"Um 1550 erbautes Rathaus.","images":[{"imageName":"images/thumb/4/43/Rathaus_alt.jpg/640px-Rathaus_alt.jpg", "imageDescription":" "}]},{"lang":"en","title":"First City Hall","text":"City hall built about 1550."},{"title":"Info ", "text":"Hauptplatz 1\n8010 Graz\nSteiermark\n\u00d6sterreich\n\n47.070725, 15.438458333333\nmehr unter http:\/\/baugeschichte.at\/Hauptplatz 1","images":[{"imageName":"skins/common/images/logo_baugeschichte.png", "imageDescription":""}]}]}

**Comment by Flexmaen** [comment]
Die 3. Sprache wurde zwischendurch abgeschalten, weil das nicht funktioniert hat.
Jetzt sollte sie wieder an sein - ich sehe du hast da einen Bug behoben:
https://github.com/gschwann/Baugeschichte/issues/93

Kannst du mal schauen ob das mit dem dritten Bild nun auch klappt, dann können wir das schließen.

**Comment by gschwann** [comment]
Fixed with commit 5e961d9
