### ISSUE TITLE
umschalten bei drei Sprachen

### ISSUE THREAD

**Issue by Flexmaen** [gschwann/Baugeschichte#90]
Drei Sprachen gehen generell, Beispiel:
http://baugeschichte.at/Magyar_Ede_tér_2_(Szeged)

Da wird Deutsch und Englisch richtig erkannt, bei Ungarisch steht L1. Das passt auch, lässt sich dann aber offenbar nicht mehr antippen um auf eine andere Sprache zu schalten.

Eventuell ein Schaltfeld machen (und optional die Fahne für den entsprechenden Sprachcode angeben?).

**Comment by gschwann** [comment]
Gefixt mit commit b8c56b433ad3c87cf99e981b0a5164d1cbc74154
