### ISSUE TITLE
src/qml/DetailsView.qml

### ISSUE THREAD

**Issue by Citydampf** [gschwann/Baugeschichte#93]
line 340    if (detailsModel.modelEN.count > 0)  kommt 2 mal ?? 
sollte vielleicht  if (detailsModel.modelS1.count > 0) 
 function twoOrMoreLanguages() {
                var languages = 0;
                if (detailsModel.modelDE.count > 0) {
                    languages += 1;
                }
                if (detailsModel.modelEN.count > 0) {
                    languages += 1;
                }
                if (detailsModel.modelEN.count > 0) {
                    languages += 1;
                }
                return languages >= 2;
            }
}

**Comment by gschwann** [comment]
Stimmt - klassischer copy/paste Fehler :(
Gefixt mit 5e961d9d63f5fb9f5b9e41e60fb563e4f274772f
